### ISSUE TITLE
Cant get skill running

### ISSUE THREAD

**Issue by faebeee** [jcasoft/GoogleGmailSkill#1]
I freshly installed mycroft. after following the installation steps of this skill i get this error

Ubuntu Gnome 17.04 64bit

Any ideas?

`➜  ~ cd  $HOME/.mycroft/skills

➜  skills python GoogleGmailSkill
python GoogleGmailSkill

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/fabs/.mycroft/skills/GoogleGmailSkill/__main__.py", line 17, in <module>
    from apiclient import discovery
ImportError: cannot import name discovery
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/fabs/.mycroft/skills/GoogleGmailSkill/__main__.py", line 17, in <module>
    from apiclient import discovery
ImportError: cannot import name discovery
➜  skills 
`

**Comment by jcasoft** [comment]
I will make the necessary changes to work with the latest version of mycroft and try to upload it this weekend

**Comment by jcasoft** [comment]
The Google Gmail Skill has been corrected and updated to be installed with MSM

msm install https://github.com/jcasoft/GoogleGmailSkill.git

The skill has been corrected and updated to be installed with MSM, you can see the instructions in the repository: 
https://github.com/jcasoft/GoogleGmailSkill

**Comment by jcasoft** [comment]
GoogleGmailSkill is available to be installed by MSM and with manual method for Mark1
